Fix up raw_input/input compatability issues across Python 2/3.
'raw_input' has been renamed to 'input' in python3. Fixes a local-variable
clobber stemming from unintentional overload:

Traceback (most recent call last):
  File "./aristotle_easy_installer.py", line 195, in <module>
    sys.exit(main())
  File "./aristotle_easy_installer.py", line 192, in main
    return setup_mdr(**kwargs)
  File "./aristotle_easy_installer.py", line 47, in setup_mdr
    name = valid_input("Enter the system name for your registry (lowercase letters and underscores ONLY): ",name_regex)
  File "./aristotle_easy_installer.py", line 39, in valid_input
    check = input(prompt)
UnboundLocalError: local variable 'input' referenced before assignment

Signed-off-by: Paul Mundt <paul.mundt@adaptant.io>