Fix up string hashing TypeError in Python3
Under Python3 strings are no longer unicode-implicit and require explicit
encoding for byte-addressability by the hashing algorithm.

Traceback (most recent call last):
  File "./aristotle_easy_installer.py", line 197, in <module>
    sys.exit(main())
  File "./aristotle_easy_installer.py", line 194, in main
    return setup_mdr(**kwargs)
  File "./aristotle_easy_installer.py", line 75, in setup_mdr
    generate_secret_key(name)
  File "./aristotle_easy_installer.py", line 105, in generate_secret_key
    gen_key = hashlib.sha224(str(getrandbits(128))).hexdigest() # This is probably not cryptographically secure, not for production.
TypeError: Unicode-objects must be encoded before hashing

Signed-off-by: Paul Mundt <paul.mundt@adaptant.io>