Fix for raise syntax no longer accepting comma-separated arguments
Fixes up syntax error encountered when running the installer:

  File "./aristotle_easy_installer.py", line 173
    except getopt.error, msg:
                       ^
SyntaxError: invalid syntax

Signed-off-by: Paul Mundt <paul.mundt@adaptant.io>